export const DATE_ERROR_MESSAGES = {
  PARSE_ERROR: 'DATE_ERROR_PARSE',
  FORMAT_ERROR: 'DATE_ERROR_FORMAT',
  EMPTY_OR_INVALID: 'DATE_ERROR_EMPTY_OR_INVALID',
  INVALID_FORMAT: 'DATE_ERROR_INVALID_FORMAT',
  NULL_OR_UNDEFINED: 'DATE_ERROR_NULL_OR_UNDEFINED',
};
