export {
  getPatientById,
  getFormattedPatientById,
  searchPatientByNameOrId,
  searchPatientByCustomAttribute,
  searchAppointmentsByAttribute,
  getPrimaryIdentifierType,
  createPatient,
  createVisit,
  getActiveVisitByPatient,
  getIdentifierData,
  getGenders,
  getAddressHierarchyEntries,
  getVisitTypes,
  getVisitLocationUUID,
} from './patientService';
export {
  type FormattedPatientData,
  type PatientSearchResultBundle,
  type PatientSearchResult,
  type IdentifierSource,
  type IdentifierType,
  type IdentifierTypesResponse,
  type CreatePatientRequest,
  type CreatePatientResponse,
  type VisitData,
  type PatientName,
  type PatientAddress,
  type PatientIdentifier,
  type PatientAttribute,
  type AddressHierarchyEntry,
  type VisitType,
  type VisitLocationResponse,
  type ActiveVisit,
} from './models';
