export {
  getPatientById,
  getFormattedPatientById,
  searchPatientByNameOrId,
  searchPatientByCustomAttribute,
  getPrimaryIdentifierType,
  createPatient,
  createVisit,
  getActiveVisitByPatient,
  getIdentifierData,
  getGenders,
  getAddressHierarchyEntries,
  getVisitTypes,
} from './patientService';
export {
  type FormattedPatientData,
  type PatientSearchResultBundle,
  type PatientSearchResult,
  type IdentifierSource,
  type IdentifierType,
  type IdentifierTypesResponse,
  type CreatePatientRequest,
  type CreatePatientResponse,
  type CreateVisitRequest,
  type PatientName,
  type PatientAddress,
  type PatientIdentifier,
  type PatientAttribute,
  type AddressHierarchyEntry,
  type VisitType,
} from './models';
