/**
 * Configuration-related error messages
 * Used for consistent error handling across the application
 */
export const CONFIG_ERROR_MESSAGES = {
  CONFIG_NOT_FOUND: 'CONFIG_ERROR_NOT_FOUND',
  VALIDATION_FAILED: 'CONFIG_ERROR_VALIDATION_FAILED',
  SCHEMA_VALIDATION_FAILED: 'CONFIG_ERROR_SCHEMA_VALIDATION_FAILED',
};

/**
 * Error title constants for notifications
 */
export const ERROR_TITLES = {
  CONFIG_ERROR: 'ERROR_CONFIG_TITLE',
  VALIDATION_ERROR: 'ERROR_VALIDATION_TITLE',
  DASHBOARD_ERROR: 'ERROR_DASHBOARD_CONFIG_TITLE',
  CONSULTATION_ERROR: 'ERROR_CONSULTATION_TITLE',
};

export const DATE_ERROR_MESSAGES = {
  PARSE_ERROR: 'DATE_ERROR_PARSE',
  FORMAT_ERROR: 'DATE_ERROR_FORMAT',
  EMPTY_OR_INVALID: 'DATE_ERROR_EMPTY_OR_INVALID',
  INVALID_FORMAT: 'DATE_ERROR_INVALID_FORMAT',
  NULL_OR_UNDEFINED: 'DATE_ERROR_NULL_OR_UNDEFINED',
};

export const COMMON_ERROR_MESSAGES = {
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
};

export const CONSULTATION_ERROR_MESSAGES = {
  INVALID_DIAGNOSIS_PARAMS: 'CONSULTATION_ERROR_INVALID_DIAGNOSIS_PARAMS',
  INVALID_ENCOUNTER_SUBJECT: 'CONSULTATION_ERROR_INVALID_ENCOUNTER_SUBJECT',
  INVALID_ENCOUNTER_REFERENCE: 'CONSULTATION_ERROR_INVALID_ENCOUNTER_REFERENCE',
  INVALID_PRACTITIONER: 'CONSULTATION_ERROR_INVALID_PRACTITIONER',
  INVALID_ALLERGY_PARAMS: 'CONSULTATION_ERROR_INVALID_ALLERGY_PARAMS',
  INVALID_CONDITION_PARAMS: 'CONSULTATION_ERROR_INVALID_CONDITION_PARAMS',
};

export const AUDIT_LOGS_ERROR_MESSAGES = {
  DASHBOARD_AUDIT_VIEW_FAILURE: "DASHBOARD_AUDIT_VIEW_FAILURE"
};

export const AUDIT_LOG_ERROR_MESSAGES = {
  UNKNOWN_EVENT_TYPE: 'AUDIT_LOG_ERROR_UNKNOWN_EVENT_TYPE',
  LOG_FAILED: 'AUDIT_LOG_ERROR_LOG_FAILED',
  UNKNOWN_ERROR: 'AUDIT_LOG_ERROR_UNKNOWN_ERROR',
  GLOBAL_PROPERTY_FETCH_FAILED: 'AUDIT_LOG_ERROR_GLOBAL_PROPERTY_FETCH_FAILED',
  STATUS_CHECK_FAILED: 'AUDIT_LOG_ERROR_STATUS_CHECK_FAILED',
  DASHBOARD_VIEW_NOT_LOGGED: 'AUDIT_LOG_ERROR_DASHBOARD_VIEW_NOT_LOGGED',
  ENCOUNTER_EDIT_FAILED: 'AUDIT_LOG_ERROR_ENCOUNTER_EDIT_FAILED',
  AUDIT_LOGGING_FAILED: 'AUDIT_LOG_ERROR_AUDIT_LOGGING_FAILED',
  DASHBOARD_VIEW_FAILED: 'AUDIT_LOG_ERROR_DASHBOARD_VIEW_FAILED',
  ENCOUNTER_SAVE_FAILED: 'AUDIT_LOG_ERROR_ENCOUNTER_SAVE_FAILED',
};

export const AUDIT_LOG_MESSAGES = {
  NO_DASHBOARD_SECTIONS: 'AUDIT_LOG_MESSAGE_NO_DASHBOARD_SECTIONS',
};
