import i18next from 'i18next';

export const DATE_ERROR_MESSAGES = {
  PARSE_ERROR: i18next.t('DATE_ERROR_PARSE'),
  FORMAT_ERROR: i18next.t('DATE_ERROR_FORMAT'),
  EMPTY_OR_INVALID: i18next.t('DATE_ERROR_EMPTY_OR_INVALID'),
  INVALID_FORMAT: i18next.t('DATE_ERROR_INVALID_FORMAT'),
  NULL_OR_UNDEFINED: i18next.t('DATE_ERROR_NULL_OR_UNDEFINED'),
} as const;
