LoadModule rewrite_module modules/mod_rewrite.so
Alias /bahmni-v2 "/usr/local/apache2/htdocs/bahmni-v2"
    <Directory "/usr/local/apache2/htdocs/bahmni-v2">
        Require all granted
        AllowOverride All
        Options -Indexes +FollowSymLinks

        # Enable React routing by redirecting all requests to index.html
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ /bahmni-v2/index.html [L]
    </Directory>
