export const COMMON_ERROR_MESSAGES = {
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
};

export const ERROR_TITLES = {
  CONFIG_ERROR: 'ERROR_CONFIG_TITLE',
  VALIDATION_ERROR: 'ERROR_VALIDATION_TITLE',
  DASHBOARD_ERROR: 'ERROR_DASHBOARD_CONFIG_TITLE',
  CONSULTATION_ERROR: 'ERROR_CONSULTATION_TITLE',
};

export const CONSULTATION_ERROR_MESSAGES = {
  INVALID_DIAGNOSIS_PARAMS: 'CONSULTATION_ERROR_INVALID_DIAGNOSIS_PARAMS',
  INVALID_ENCOUNTER_SUBJECT: 'CONSULTATION_ERROR_INVALID_ENCOUNTER_SUBJECT',
  INVALID_ENCOUNTER_REFERENCE: 'CONSULTATION_ERROR_INVALID_ENCOUNTER_REFERENCE',
  INVALID_PRACTITIONER: 'CONSULTATION_ERROR_INVALID_PRACTITIONER',
  INVALID_ALLERGY_PARAMS: 'CONSULTATION_ERROR_INVALID_ALLERGY_PARAMS',
  INVALID_CONDITION_PARAMS: 'CONSULTATION_ERROR_INVALID_CONDITION_PARAMS',
};